Azure/terraform-azurerm-avm-template

README.md
_header.md
examples/default/README.md
examples/default/main.tf
locals.tf
main.privateendpoint.tf
main.telemetry.tf
main.tf
outputs.tf
variables.tf

A number of suggestions
- remove "enable telemetry" from the default example, it is already set by default.
- add the required AVM interfaces for things like private endpoints, roles, locks etc.
This also includes some the previous suggestion regarding making the location an optional param.
I note that the line endings in the template are CRLF, when I run make docs & make fmt this makes for a messy commit, maybe it should be LF in the template tho?
more as a discussion point - I'm finding I'm repeating the same work each time i start... 🙂

suggested template adjustments

---

examples/default/README.md
examples/default/main.tf
locals.tf
main.privateendpoint.tf
main.tf

hi @matt-FFFFFF - missed this one - we need a 'try' around the location otherwise in the case a location is specified, the data block errors.  I think this proposal is the best.
I've E2E tested it on my container registry which has a mix of locations specified & not:
https://github.com/kewalaka/terraform-azurerm-avm-res-containerregistry-registry/actions/runs/7065336984

fix: bug when location is specified

---

.devcontainer/devcontainer.json

.. uses the same devcontainer.json found in terraform verified modules & other lonegunmanb repos.
as an aside, it would be great if newres could be added to the azterraform container image - i can't find the appropriate repo to add an issue onto for that.

Add a dev container

---

.github/workflows/e2e.yml

Remove redundant parallel concurrency limit

chore: remove matrix concurrency limit

---

README.md
examples/default/README.md
examples/default/main.tf
locals.telemetry.tf
main.privateendpoint.tf
main.telemetry.tf
main.tf
outputs.tf
terraform.tf
variables.tf

[TFNFR26](https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr26---category-code-style---providers-must-be-declared-in-the-required_providers-block-in-terraformtf-and-must-have-a-constraint-on-minimum-and-maximum-major-version)

Aligning to TFNFR26

---

main.tf
variables.tf

feat: make location mandatory

---

examples/default/main.tf

fix: example location

---

.github/workflows/linting.yml

feat: add avmfix check and lintcomplete step

---

.editorconfig
.gitattributes
.vscode/settings.json

Add tabsize and eol

---

.github/actions/e2e-getexamples/action.yml

fixes #109 
Removes external dependency and uses tooling available on GH runners to produce JSON directory listing

feat: remove jsonls and simplify

---

locals.telemetry.tf

Delete deprecated file

---

locals.version.tf.json

Remove locals telemetry

---

.terraform-docs.yml

remove providers section from tf docs as it's a duplicate of requriements

---

.terraform-docs.yml
examples/.terraform-docs.yml
modules/.terraform-docs.yml

Loosen the version constraint so that it works with container updates and make it work with the current version in the container.

Fix Terraform Docs version issue

---

examples/default/main.tf

feat: move to utility module for regions

---

.github/actions/1es-runner-auth-docker/action.yml
.github/actions/avmfix/action.yml
avm
avm.bat

Adds new action to simplify the centralise running commands on 1ES runner pool (the new terraform test workflow will need the same code).
Also fixes bug in avmfix (missing quotes)

feat: add GH action for local testing

---

avm

feat: azurerm 4.0

---

avm.bat

feat: azurerm 4.0 (avm.bat)

---

.github/actions/linting/action.yml

feat: azurerm 4.0 (lint action)

---

.github/actions/linting/action.yml

feat: azurerm 4.0 (mock for lint ci)

---

.github/workflows/e2e.yml

bug: workflow_dispatch for e2e tests check for fork fails

---

.github/actions/e2e-getexamples/action.yml

bug: fix missing json flag

---

.github/actions/e2e-getexamples/action.yml

chore: debug e2e examples

---

.github/actions/e2e-getexamples/action.yml

fix: include hidden files

---

avm
avm.bat

map `GITHUB_TOKEN` env into container

---

.github/workflows/test-examples-template.yml
.gitignore
avm
avm.bat

add conftest before e2e test

---

.github/workflows/test-examples-template.yml

Tested locally with
```
docker run --rm  -v $(pwd):/src -w /src -e TF_IN_AUTOMATION mcr.microsoft.com/azterraform:latest make conftest
```

fix: conftest job

---

.github/workflows/test-examples-template.yml
examples/default/main.tf
examples/ignore_example_for_e2e/main.tf

Add missing environment setting in e2e tests

fix: missing environment

---

.github/workflows/test-examples-template.yml

do not proceed e2e tests if conftest failed

---

README.md
_header.md

Remove the obsolete instructions from the read me.

chore: fix read me instructions

---

avm

add env var AVM_NO_CONTAINER_PULL to bypass image pull
